version: '3.5'

services:
    ms-sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        environment:
           SA_PASSWORD: "Your_password123"
           ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"

    avio-api:
        image: avio-api:latest
        ports:
            - "5000:80"
        depends_on: 
            - ms-sql-server

    car-api: 
        image: car-api:latest
        ports:
             - "5001:80"
        depends_on: 
             - ms-sql-server

    auth-api: 
        image: auth-api:latest
        ports:
            - "5002:80"
        depends_on: 
            - ms-sql-server  